# Spring Boot Configuration
spring.application.name=videoclubweb
server.port=8080

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@videoclub_high?TNS_ADMIN=C:/wallet/videoclub
spring.datasource.username=ADMIN
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
